# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: fhanssen-acnviewer-1.0dev
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=2.7
  # python \
  # git \
  #- conda-forge::git=2.28.0
  # wget \
  # python-dev \
  # python-pip \
  # python-virtualenv \

  # r-base-core \
  - conda-forge::r-base=4.0.2 # 3.4.1
  # r-base-dev \
  # r-cran-ggplot2 \
  - conda-forge::r-ggplot2=3.3.2 #2.2.1
  # r-cran-gplots \
  - conda-forge::r-gplots=3.1.0 #3.0.1
  # r-cran-rcolorbrewer \
  #- conda-forge::r-rcolorbrewer=1.1_2
  # r-cran-plotrix \
  - conda-forge::r-plotrix=3.7
  - conda-forge::r-rcurl=1.98_1_2 #1.95_4.11
  # r-bioc-limma \
  - bioconda::bioconductor-limma=3.44.1 #3.36.5
  # x11-utils \
  - conda-forge::xorg-libx11=1.6.12
  # && rm -rf /var/lib/apt/lists/*
  
  - bioconda::samtools=1.10 #0.1.19
  - bioconda::ascat=2.5.2
  - bioconda::sequenza-utils=3.0.0
  - bioconda::r-sequenza=3.0.0
  - conda-forge::r-squash=1.0.9
  - bioconda::bioconductor-copynumber=1.28.0 #1.20.0
  - bioconda::bioconductor-cghregions=1.46.0 #1.38.0
  # - conda-forge::make=4.3
  - conda-forge::r-glue=1.4.2 #1.3.0
  - conda-forge::r-rlang=0.4.7 #0.3.0.1
  - conda-forge::r-pkgconfig=2.0.3 #2.0.2
  - conda-forge::r-ellipsis=0.3.1 #0.3.0
  - conda-forge::r-vctrs=0.3.4
  - conda-forge::r-hms=0.5.3
  - conda-forge::r-r6=2.4.1
  - conda-forge::r-clipr=0.7.0
  - conda-forge::r-crayon=1.3.4
  - conda-forge::r-bh=1.72.0_3
  - conda-forge::r-pbapply=1.4_3
  - conda-forge::r-iotools=0.3_1
  - conda-forge::r-readr=1.3.1
  - conda-forge::r-seqminer=8.0

  #‘ellipsis’, ‘vctrs’, ‘hms’, ‘R6’, ‘clipr’, ‘crayon’, ‘BH’, ‘pbapply’, ‘iotools’, ‘readr’, ‘seqminer’


